Builtin source
AnonymusRaccoon/ash pull request #32
Opened 2020-05-01 10:32 UTC by TrueBluub

two branches at once because I didn't go back to master to do it ><, builtin source and builtin which/where. to add aliases when they are added to the shell. Naming of functions may still be bad.

2020-05-01 12:56 UTC, zoriya requested changes
Things that need to be changed:
- You don't check your mallocs (ex: the start_script function).
- You should use functions name that won't conflict with other files or make them statics. Ex: start_script is a name that could be used for anything.

The rest is good !

PS: The source branch should only contain the source built-in and not the where and which since they are not merged with master yet.

2020-05-01 14:45 UTC, zoriya approved these changes
Good. I think we should wait for the where/which to be merged with master before merging this one but we are good.

2020-05-01 14:53 UTC, melefo approved these changes

2020-05-01 14:56 UTC, Octopus773 approved these changes

2020-05-05 13:46 UTC, Arthi-chaud approved these changes

2020-05-07 10:50 UTC, AnonymusRaccoon commented
That seems good to me but keep in mind that $1, $2, $@ etc should be handled like other variables so this should be changed when the parser will handle variables.

2020-05-11 07:48 UTC, Arthi-chaud approved these changes

2020-05-11 10:46 UTC, merged