Aliases
AnonymusRaccoon/ash pull request #44
Opened 2020-05-12 06:41 UTC by Arthi-chaud

Aliases and unaliases working
However, since the inhibitors and parentheses are still not managed, multiple command aliases can not be excuted since they are put between parentheses. If multiple arg to alias command, need to be separated by inhibitor

2020-05-12 08:42 UTC, Octopus773 approved these changes
Some functions aren't norm friendly (too long) but this seems ok

2020-05-12 08:42 UTC, Octopus773 commented on src/builtin/builtin_alias.c
> +        return (1);
if you want to keep an int return in the function errors are usually less than 0 (ex: -1) otherwise use a bool type return

2020-05-12 08:54 UTC, GitBluub approved these changes

2020-05-12 09:18 UTC, AnonymusRaccoon commented on src/builtin/builtin_alias.c
> +    if (command[1])
You are doing a my_calloc here. If you want to memset your malloced memory to 0, use calloc.

2020-05-12 09:21 UTC, melefo approved these changes

2020-05-12 09:28 UTC, zoriya requested changes
Use calloc instead of malloc and a for to memset at 0.
Instead of using a char as a bool to tell if the alias has been removed, remove the alias from the list.
Use printf instead of many writes (do not forget to flush the buffer if needed).
Your aliases can't handle redirections since you handle them after the redirection handling (they can't be globbed ether).

2020-05-13 12:07 UTC, zoriya approved these changes
Good! Only need to add redirections as said on #45 but it will be for another PR.

2020-05-13 12:08 UTC, merged